// imports/ui/App.vue

<template>
  <div id="app">

    <Thing v-for="thing in getTheThings" v-bind:label="thing.text"/>

  </div>
</template>

<script>
import Thing from './components/Thing.vue';
import { Things } from '../api/things.js';
import { Meteor } from 'meteor/meteor';

export default {
  name: 'app',
  components: {
    Thing
  },
  computed: {

      filterThings: function (things) {

          // remove completed items from the array if hideCompleted is checked.
          if (this.hideCompleted) {
              things = things.filter(thing => !thing.checked);
          }

          // if the thing belongs to the current user, show the 'private' button
          return things.map((thing) => {
              const currentUserId = this.props.currentUser && this.props.currentUser._id;
              thing.showPrivateButton = thing.owner === currentUserId;
              return thing;
          });
      }
  },
  methods: {
      insertSomething: function() {
          const text = "test text";
          const quantity = 5;

          Meteor.call('things.insert', text, quantity);
          //console.log('inserting data');
          return text;
      }
  },
  meteor: {
    $subscribe: {
        'Things': []
    },
    getTheThings() {
        let things = Things.find({}, { sort: { createdAt: -1 } }).fetch();
        return things;
    }


  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// imports/ui-react-old/App.js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { Meteor } from 'meteor/meteor';

import { withTracker } from 'meteor/react-meteor-data';

import { Things } from '../api/things.js';

import Thing from './Thing.js';
import AccountsUIWrapper from './AccountsUIWrapper.js';

// App component - represents the whole app
class App extends Component {
    constructor(props) {
        super(props);

        this.state = {
            hideCompleted: false,
        };
    }
    handleSubmit(event) {
        event.preventDefault();

        // Find the text field via the React ref
        const text = ReactDOM.findDOMNode(this.refs.textInput).value.trim();
        const quantity = parseInt(ReactDOM.findDOMNode(this.refs.quantity).value);
        Meteor.call('things.insert', text, quantity);

        // Clear form
        ReactDOM.findDOMNode(this.refs.textInput).value = '';
        ReactDOM.findDOMNode(this.refs.quantity).value = '';
    }
    toggleHideCompleted() {
        this.setState({
            hideCompleted: !this.state.hideCompleted,
        });
    }
    renderThings() {
        let filteredThings = this.props.things;
        if (this.state.hideCompleted) {
            filteredThings = filteredThings.filter(thing => !thing.checked);
        }
        return filteredThings.map((thing) => {
            const currentUserId = this.props.currentUser && this.props.currentUser._id;
            const showPrivateButton = thing.owner === currentUserId;

            return (
                <Thing
                    key={thing._id}
                    thing={thing}
                    showPrivateButton={showPrivateButton}
                />
            );
        });
    }

    render() {
        return (
            <div className="container">
                <header>
                    <h1>Thing List ({this.props.incompleteCount})</h1>
                    <label className="hide-completed">
                        <input
                            type="checkbox"
                            readOnly
                            checked={this.state.hideCompleted}
                            onClick={this.toggleHideCompleted.bind(this)}
                        />
                        Hide Checked Things
                    </label>
                    <AccountsUIWrapper />

                    { this.props.currentUser ?
                        <form className="new-thing" onSubmit={this.handleSubmit.bind(this)} >
                            <input
                                type="text"
                                ref="textInput"
                                placeholder="Type to add a new thing"
                            />
                            <input
                                type="number"
                                ref="quantity"
                                placeholder="How Many"
                            />
                            <input type="submit" value="Swap It!" class="swap-button"/>
                        </form> : ''
                    }
                </header>

                <ul>
                    {this.renderThings()}
                </ul>
            </div>
        );
    }
}

export default withTracker(() => {
    Meteor.subscribe('things');

    return {
        things: Things.find({}, { sort: { createdAt: -1 } }).fetch(),
        incompleteCount: Things.find({ checked: { $ne: true } }).count(),
        currentUser: Meteor.user(),
    };
})(App);
